title = "Joaquin Metayer"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
